name: Elisp Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Eamcs
        uses: purcell/setup-emacs@master
        with:
         version: 26.1
        
      - name: Emacs Lisp check
        uses: leotaku/elisp-check@v1.3
        with:
          file: d2-mode.el
          warnings_as_errors: true
