name: Elisp Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        emacs-version:
          - 26.3
          - 27.2
          - 28.2
          - snapshot

    steps:
      - uses: actions/checkout@v3

      - name: Setup Emacs
        uses: jcs090218/setup-emacs@master
        with:
         version: ${{ matrix.emacs-version }}
        
      - name: Emacs Lisp check
        uses: leotaku/elisp-check@v1.3
        with:
          file: d2-mode.el
          warnings_as_errors: true
